import {ArrowUpRight,BarChart3,Crosshair,Target,Trophy,Users,Zap} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {watchPlayers,type Player} from "../services/data";

const num=(v:any)=>{const n=Number(String(v??"").replace(/[^0-9.+-]/g,""));return Number.isFinite(n)?n:0};
const stat=(p:Player,keys:string[])=>{for(const k of keys){if(p[k]!==undefined&&p[k]!==null&&p[k]!=="")return num(p[k])}return 0};
function PlayerAnalytics({p}:{p:Player}){const name=p.ign||p.playerName||p.name||"PLAYER";const kd=stat(p,["kd","kD","kdr","K/D"]);const booyahs=stat(p,["booyahs","wins","winCount"]);const matches=stat(p,["matches","matchCount","totalMatches"]);const hs=stat(p,["headshot","headshots","headshotPercent","headshotRate"]);const winRate=matches?Math.min(100,(booyahs/matches)*100):0;return <article className="analytics-player"><div className="analytics-player-head"><div><span>{p.role||"4FU PLAYER"}</span><h3>{name}</h3></div><b>{p.status||"ROSTER"}</b></div><div className="analytics-stat-row"><div><strong>{kd||"—"}</strong><small>K/D</small></div><div><strong>{booyahs||"—"}</strong><small>BOOYAHS</small></div><div><strong>{matches||"—"}</strong><small>MATCHES</small></div><div><strong>{hs?hs+"%":"—"}</strong><small>HEADSHOT</small></div></div><div className="analytics-bar"><i style={{width:`${winRate}%`}}/><span>WIN RATE {winRate?winRate.toFixed(0):"—"}%</span></div></article>}
export function Analytics(){
 const [players,setPlayers]=useState<Player[]>([]);useEffect(()=>watchPlayers(setPlayers),[]);
 const summary=useMemo(()=>{const kd=players.map(p=>stat(p,["kd","kD","kdr","K/D"])).filter(Boolean);const booyahs=players.reduce((s,p)=>s+stat(p,["booyahs","wins","winCount"]),0);const matches=players.reduce((s,p)=>s+stat(p,["matches","matchCount","totalMatches"]),0);const hs=players.map(p=>stat(p,["headshot","headshots","headshotPercent","headshotRate"])).filter(Boolean);return {avgKd:kd.length?(kd.reduce((a,b)=>a+b,0)/kd.length).toFixed(2):"—",booyahs,matches,avgHs:hs.length?(hs.reduce((a,b)=>a+b,0)/hs.length).toFixed(1)+"%":"—"}},[players]);
 return <div className="page analytics-page"><div className="page-hero compact"><span className="kicker">4FU ANALYTICS / LIVE INTELLIGENCE</span><h1>NUMBERS<br/><em>DON'T LIE.</em></h1><p>Roster performance, combat efficiency and competitive output — normalized from the live 4FU player dataset.</p></div>
  <section className="analytics-summary"><div><Crosshair/><b>{summary.avgKd}</b><span>AVERAGE K/D</span></div><div><Trophy/><b>{summary.booyahs}</b><span>TEAM BOOYAHS</span></div><div><BarChart3/><b>{summary.matches}</b><span>TOTAL MATCHES</span></div><div><Target/><b>{summary.avgHs}</b><span>AVG HEADSHOT</span></div></section>
  <section className="analytics-layout"><div><div className="analytics-section-head"><div><span className="kicker">ROSTER PERFORMANCE</span><h2>PLAYER <em>BREAKDOWN.</em></h2></div><span className="analytics-live"><i/> FIRESTORE LIVE</span></div><div className="analytics-list">{players.map(p=><PlayerAnalytics key={p.id} p={p}/>)}</div>{!players.length&&<div className="media-note">Loading live player analytics…</div>}</div>
   <aside className="analytics-side"><div className="analytics-side-head"><Zap/><span>PERFORMANCE CORE</span></div><div className="analytics-side-item"><Users/><div><b>{players.length}</b><span>ROSTER SIZE</span></div></div><div className="analytics-side-item"><Trophy/><div><b>{players.filter(p=>p.owner).length}</b><span>LEADERS</span></div></div><div className="analytics-side-item"><BarChart3/><div><b>{players.filter(p=>String(p.status||"").toLowerCase().includes("online")).length}</b><span>ONLINE SIGNALS</span></div></div><a className="primary" href="/team">VIEW FULL ROSTER <ArrowUpRight size={15}/></a></aside>
  </section>
 </div>
}