import { Send, Bell, Hash, ShieldAlert, CircleDot, Smartphone } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";
import { auth,db } from "../services/firebase/client";
import { request4FUPushPermission, listen4FUForegroundMessages } from "../services/firebase/messaging";
import { watchChat,watchNotifications,watchPlayerByAuth,type ChatMessage,type AppNotification,type Player } from "../services/data";

export function Comms(){
 const [messages,setMessages]=useState<ChatMessage[]>([]),[notes,setNotes]=useState<AppNotification[]>([]),[player,setPlayer]=useState<Player|null>(null),[text,setText]=useState(""),[sending,setSending]=useState(false),[pushState,setPushState]=useState("ENABLE PHONE ALERTS"),[toast,setToast]=useState("");
 useEffect(()=>watchChat(setMessages),[]); useEffect(()=>watchNotifications(setNotes),[]);
 useEffect(()=>{let u=()=>{};return onAuthStateChanged(auth,user=>{u();u=user?watchPlayerByAuth(user.uid,user.email,setPlayer):()=>{}})},[]);
 useEffect(()=>{let off=()=>{}; listen4FUForegroundMessages(payload=>{const d=payload?.data||{};setToast(d.title||payload?.notification?.title||"New 4FU notification");setTimeout(()=>setToast(""),4500)}).then(u=>off=u);return()=>off()},[]);
 const unread=useMemo(()=>notes.filter(n=>!n.isRead).length,[notes]);
 async function enablePush(){try{setPushState("CONNECTING…");const r=await request4FUPushPermission();setPushState(r.permission==="granted"?"PHONE ALERTS ON":r.permission==="denied"?"BLOCKED":"UNAVAILABLE")}catch(e){console.error(e);setPushState("TRY AGAIN")}}
 async function send(){const value=text.trim(),user=auth.currentUser;if(!value||!user||!player||sending)return;if(value.length>300)return;setSending(true);try{await addDoc(collection(db,"chat"),{text:value,playerId:player.id,playerName:player.ign||player.playerName||player.name||"Player",playerImage:player.image||player.photo||player.profileImage||"",playerEmail:user.email,createdAt:serverTimestamp()});setText("")}catch(e){console.error(e)}finally{setSending(false)}}
 return <div className="page"><div className="page-hero"><span className="kicker">4FU COMMS / REALTIME</span><h1>STAY <em>CONNECTED.</em></h1><p>Live Fire Chat and team notifications, using the same existing Firestore channels.</p><button className="admin-primary-link" onClick={enablePush}><Smartphone size={15}/> {pushState}</button></div>
 <div className="comms-layout"><section className="chat-panel"><div className="chat-head"><div><b><CircleDot size={11}/> FIRE CHAT</b><span>REALTIME • {messages.length} messages</span></div><Hash/></div><div className="chat-feed">{messages.map(m=><div className={"chat-row "+(m.playerId===player?.id?"mine":"")} key={m.id}><img src={m.playerImage||"https://fire-united.web.app/images/logo/logo.png"} onError={e=>{e.currentTarget.style.display="none"}}/><div><b>{m.playerName||"4FU PLAYER"}</b><p>{m.text}</p></div></div>)}{!messages.length&&<div className="chat-empty">🔥 No messages yet. Start the fire.</div>}</div><div className="chat-compose"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={player?"Message the squad…":"Login as a player to chat"}/><button disabled={!player||sending} onClick={send}><Send size={16}/></button></div></section>
 <aside className="notice-panel"><div className="panel-title"><span>NOTIFICATION CENTER</span><Bell/><b>{unread}</b></div>{notes.slice(0,12).map(n=><article className={"notice "+(n.priority==="high"?"priority":"")} key={n.id}>{n.priority==="high"?<ShieldAlert/>:<Bell/>}<div><b>{n.title||"4FU Notification"}</b><p>{n.message||n.body||""}</p></div></article>)}{!notes.length&&<div className="media-note">No notifications yet.</div>}</aside></div>{toast&&<div className="fourfu-toast"><Bell size={15}/>{toast}</div>}</div>
}